server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # PosgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/product_management
    username: postgres
    password: admin
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# JWT Configuration
jwt:
  signerKey: cnf61zcey4yE0RfDwk3yOAgi+CRVsjb1LPQP0O9e0GyLworFq8IthDFERD/0bxy2
  valid-duration: 3600
  refreshable-duration: 86400

file:
  directory: ./uploads/
  max-size: 10MB